# GET METHOD
GET http://localhost:5000/api/users/user

###

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name" : "Brad",
    "email": "brad@gmail.com",
    "password":"abcdef"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "vina@exemple.com",
    "password":"abcdef"
}


###

GET http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "test@exemple.com",
    "password":"abcdef"
}

###

# GET METHOD WITH BEARER FOR PROTECT ROUTES
GET http://localhost:5000/api/users/user
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTVmMTU5NGIzNTdiMTc5MDg2YmU4OSIsImlhdCI6MTY1Mzk5MzgxOCwiZXhwIjoxNjU5MTc3ODE4fQ.8YqGthdG_2x1xIDtmSa40LO2xqBqYz5bg4jfwEfCc-Y

###